{% set name = "pyrogram" %}
{% set version = "2.0.106" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/Pyrogram-{{ version }}.tar.gz
  sha256: 30202995758fcb6e0f91224704ab7fedefea454297724bd70a6a71a23748c16f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - pyaes
    - pysocks

test:
  source_files:
    - tests
  imports:
    - pyrogram
  commands:
    - pytest -vv tests
    - pip check
  requires:
    - pip
    - pytest
    - pytest-asyncio
    - python {{ python_min }}

about:
  home: https://github.com/pyrogram
  summary: Elegant, modern and asynchronous Telegram MTProto API framework in Python for users and bots
  dev_url: https://github.com/pyrogram/pyrogram
  license: LGPL-3.0-or-later
  license_file:
    - COPYING.lesser
    - NOTICE
    - COPYING

extra:
  recipe-maintainers:
    - nehaljwani
